### ISSUE TITLE
Names of package and types therein

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/output-blocks#12]
Is "monad" still the correct description around here?

How about `output-blocks` as name for the package, and suitable renamings of relevant types as well?

**Comment by marcellussiegburg** [comment]
I think the name `output-monad` is wrong!

I am not very opiniated for the package name `output-blocks` seems okay to me.

But in cases like this:
```haskell
continueOrAbort :: OutputMonad m => Bool -> Bool -> LangM m -> LangM m
```
I think
```haskell
continueOrAbort :: Outputable m => Bool -> Bool -> LangM m -> LangM m
```
would be more descriptive than:
```haskell
continueOrAbort :: OutputBlocks m => Bool -> Bool -> LangM m -> LangM m
```
?

**Comment by jvoigtlaender** [comment]
`Outputable` exists as a class in some `ghc` related packages: https://hoogle.haskell.org/?hoogle=Outputable

The next best thing maybe `OutputCapable`?

**Comment by jvoigtlaender** [comment]
(And the meaning of `Outputable` in the `ghc` package seems to be different, which could create more confusion. There, a thing is outputable if that thing can be printed. Whereas the `m` above is not the thing to be printed.)

**Comment by marcellussiegburg** [comment]
Maybe the package should be named `output-capable` as well, then?

**Comment by jvoigtlaender** [comment]
I still like `output-blocks`, as it really says what all this is about, namely being able to write the output stuff in `do`-blocks in a reusable fashion. I don't think the package and the class need to be named the same.

**Comment by jvoigtlaender** [comment]
Looks reasonable.

**Comment by marcellussiegburg** [comment]
It seems renaming is the recommended way and was enough https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository.
