### ISSUE TITLE
Introduce a "mincorrect threshhold" for `multiplechoice`?

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/output-blocks#14]
In the sense that one can set a non-zero parameter (where zero would be what is currently happening) such that a submission is graded as zero if it does not exceed that parameter.

For example, so that if a student is asked to identify all wrong lines in a truth table, and simply enters an empty answer, they don't always get points proportional to the number of non-wrong lines in said table.

**Comment by marcellussiegburg** [comment]
Maybe the zero is what is confusing me here, but `multipleChoice` currently is “rejecting” solutions which are not at least 50% correct (via `printSolutionAndAssert`). Would it be enough to make this 50% configurable? Or is an absolute number of correct choices required additionally or instead?

**Comment by jvoigtlaender** [comment]
For some reason, I thought this "rejecting" was just coloring the submission as red instead of green on the Autotool pages, while not meaning that no points are given for the task. That is, a student would be able to have `0.3` points on a "rejected"/red submission.

If that's not the case, then yes, the proposal here amounts to being able to configure the 50% threshhold.
