### ISSUE TITLE
Bereitstellen weiterer Funktionen zum Zusammenstellen von Outputs

### ISSUE THREAD

**Issue by nimec01** [fmidue/output-blocks#17]
Bei fmidue/logic-tasks#167 kam die Frage auf, ob man nicht z. B. zwei Bilder nebeneinander anzeigen könnte. 

Anscheinend ist so etwas im Autotool schon implementiert ([siehe hier](https://git.uni-due.de/fmi/autotool-dev/-/blob/autotool-fmi-new/output/Autolib/Output/Type.hs?ref_type=heads#L49-L69)). Es fehlt also nur noch eine entsprechende Implementierung hier.

**Comment by marcellussiegburg** [comment]
Ich bin mir nicht sicher, was die Interpretation von dem verlinkten Link ist. Aber ich kann spoilern, dass `Beside` nicht das tut, was der Name suggeriert (zumindest in meinen Versuchen). Es gibt einen Hack, dass `Itemize` sich (via CSS) so verhält, dass es Inhalte nebeneinander darstellen kann. Das funktioniert, aber nur, solange die Zeile nicht voll ist, sonst wird umgebrochen. Die Funktion, die diese Bibliothek hier dazu bereitstellt, lautet `images`. Reicht das aus? Ansonsten wäre Anpassungsbedarf wahrscheinlich zunächst am Autotool-Ende notwendig.

**Comment by nimec01** [comment]
> Aber ich kann spoilern, dass `Beside` nicht das tut, was der Name suggeriert (zumindest in meinen Versuchen). 

Ja, das war mein Gedanke.

> Reicht das aus? Ansonsten wäre Anpassungsbedarf wahrscheinlich zunächst am Autotool-Ende notwendig.

Müsste ich mal ausprobieren.
