### ISSUE TITLE
Type of `singleChoice`

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/output-blocks#18]
Should that function really return `Rated`? It only ever gives 0 or 1 points, so no partial points are ever given.

A consequence of the current type is that in https://github.com/fmidue/logic-tasks/blob/86159b60393040b844d0862db73edd17e39dcb6d/README.md the task type `Aussagenlogik/Semantik/Wahrheitstabellen/TruthTableChooseForFormula` is marked as "Supports fractional points"

![image](https://github.com/user-attachments/assets/2316920e-689a-407f-b8e1-f00d3edfbc69)

even though that's not actually the case.

**Comment by marcellussiegburg** [comment]
Is this really a consequence of the type? Isn't this table manually maintained?

Another question is, would we want to introduce more types? What else would we like? `Bool`? `Integer`?

[Maybe in future we want combinators to combine multiple `singleChoice`s or a `singleChoice` and a `multipleChoice` to be graded together. (The thought is just in my mind since Johannes planted it there during our meeting in Leipzig. Would we want overloaded combinators then?)]

**Comment by jvoigtlaender** [comment]
> Is this really a consequence of the type? Isn't this table manually maintained?

Sure it is manually maintained. But it was filled by a human (last week) looking at the types of the `completeGrade` functions and setting a cross wherever there was a `Rated` instead of `LangM` return type.

So I would say the observation still stands: The type of that particular grading function is not as precise as it could be. It kind of claims to give a continuous grade, but then it actually contains code of the kind `if ... then 0 else 1` and never giving a grade in between. So it would make more sense to me to not claim a more general type.

(And none of the possible combination scenarious would be precluded by making the type of `singleChoice` reflect that it gives a binary rather than result on a continuous spectrum. The combinators would then have to make sure that they know how to combine or convert from such binary value.)

**Comment by jvoigtlaender** [comment]
By
> gives a binary rather 

I do not mean to let it return a "`Bool` grade", but to let it have a type like actually most `completeGrade` function so far, namely involving `LangM m`, reserving `Rated m` for those that actually do something more finegrained.

**Comment by marcellussiegburg** [comment]
I thought about how to proceed to get this update into Autotool: The other repos that use this library should create their own branches using the new version (which are kept up to date with their main branch) after it has been fixed here. In order to be incorporated into Autotool.

**Comment by jvoigtlaender** [comment]
You mean it's too late to do the switch now before the new courses "happen"?

**Comment by marcellussiegburg** [comment]
It could still be possible, but I am not sure. Also I might not be able to tend to all repositories in time. If there is no separate branch, we might not (easily) go back with one (or some) repository(/ies) if required, which could lead to missing out on last minute features.
Deployment should probably happen tomorrow at the latest?

**Comment by jvoigtlaender** [comment]
> Deployment should probably happen tomorrow at the latest?

Yes, to be able to pose Term Tasks in Modellierung.

I think the main question is whether you can manage it for `modelling-tasks`. For `logic-tasks` and `term-tasks`, @patritzenfeld and I should be able to do what is necessary.

**Comment by marcellussiegburg** [comment]
Okay, then let's proceed. I am not yet done with reversing the links. If I should not make it in time, I will create a separate branch for `modelling-tasks` tomorrow for deployment (and integrating the latest changes later this week).
